- name: Create an instance_flavor
  openstack.cloud.server:
    auto_ip: false
    availability_zone: "{{ availabiility_zone }}"
    flavor: "{{ instance_flavor }}"
    image: 
    instance_key_name: 
    instance_network:
    security_groups:
    state: present
    timeout: 600
    volumes: "{{ item.volumes }}"
    wait: yes
  #Loop over instances within the variable
  # Instances are a list of dictionaries 
  loop: "{{ instances }}"
  register: os_instance
- name: Print return information
  ansible.builtin.debug:
    var: os_instance 


#Add hosts to Ansible in-memory inventory 
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item['server']['addresses'][instance_network][0]['addr'] }}"
    grouops: COMP90024
  loop: "{{ os_instance.results }}"
  when: item.server is defined 









