- name: Create a security group
  openstack.cloud.security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'



- name: Create security group rules 
  openstack.cloud.security_group_rule:
  
