- name: Stream updates for a specific user using Mastodon API
  hosts: localhost
  vars_files:
    - variables/mastodon_vars.yaml
  tasks:

    - name: Check whether its working
      ansible.builtin.uri:
        url: "https://{{ item.name }}/api/v1/accounts/verify_credentials"
        method: GET
        headers:
          Authorization: "Bearer {{ item.access_token }}"
        
        body_format: json
        return_content: yes
        status_code: 200
      register: response
      loop: "{{ domains }}"

    - name: Print response
      debug:
        var: item.content
      loop: "{{ response.results }}"
    
    
    - name: Retrieve public toots
      ansible.builtin.uri:
        url: "https://{{ item.name }}/api/v1/timelines/public"
        method: GET
        headers:
          Authorization: "Bearer {{ item.access_token }}"
        body_format: json
        return_content: yes
        status_code: 200
      register: response
      loop: "{{ domains }}"

    - name: Print public toots
      debug:
        var: item.content
      loop: "{{ response.results }}"

    


        










  
