
- name: Create instances on MRC
  hosts: localhost
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: openstack/common
    - role: openstack/images
    - role: openstack/volume 
    - role: openstack/security-group 
    - role: openstack/instance
#    - role: openstack-volume-snapshot
#    - role: openstack-mastadon 




- name: Setting up harvester CouchDB
  become: yes
  hosts:  mrc
  gather_facts: no
  vars:
    - nodes: "{{groups['mrc'] }}"
  roles:
    - role: setup/couch
  loop: "{{ nodes }}"


- name: Harvester support CouchDB
  hosts: mrc
  gather_facts: no
  vars:
    - nodes: "{{groups['mrc'] }}"
  roles:
    - role: setup/harvester
  loop: "{{ nodes }}"










