#Common vars

availability_zone: melbourne-qh2-uom
instance_flavor: uom.mse.1c4g
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: mrc
instance_network: qh2-uom-internal
mastadon_url: 



volumes:
  - vol_name: twitter-1-1
    vol_size: 40
  - vol_name: twitter-1-2
    vol_size: 40
  - vol_name: mastadon-1-1
    vol_size: 10
  - vol_name: mastadon-1-2
    vol_size: 10
#  - vol_name: mastadon-2-1
#    vol_size: 10
#  - vol_name: mastadon-2-2
#    vol_size: 10
#  - vol_name: mastadon-2-1
#    vol_size: 10
#  - vol_name: mastadon-2-2
#    vol_size: 10

security_groups:
  - name: demo_ssh 
    description: "Demo security group for SSH access"
    protocol: tcp 
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    descrption: "Demo security group for HTTP"
    protocol: tcp 
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  


instances:
  - name: twitter-1
    volumes: ["twitter-1-1", "twitter-1-2"]
  - name: mastadon-1
    volumes: ["mastadon-1-1", "mastadon-1-2"]

#  - name: mastadon-2
#    volumes: ["mastadon-2-1", "mastadon-2-2"]