---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /data

wp_dir: wordpress


database_username: wordpress
database_user: wordpress
database_password: wordpress
mysql_root_password: "P@ssw0rd"