
availability_zone: melbourne-qh2-uom
instance_flavor: uom.mse.1c4g
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2 
instance_key_name: mrc
instance_network: qh2-uom-internal 

num_managers: 1

inventory_file: "~/inventory/inventory.ini"

volumes:
  - vol_name: mastadon-1-1
    vol_size: 10
  - vol_name: mastadon-1-2
    vol_size: 10

security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp 
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp 
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  

instances:
  - name: mastodon_server
    volumes: ["mastadon-1-1", "mastadon-1-2"]
