- name: Create a Docker service
  hosts: swarm_managers 
  become: true
  vars_files:
    - variables/mastodon_vars.yaml 
    
  tasks:
    - name: Build Docker image
      ansible.builtin.docker_image:
        name: "{{ image_name }}"
        source: /home/wagw/COMP90024-Cluster-and-Cloud-Computing-Assignment-2/harvester_node/streamer
        dockerfile: Dockerfile
        state: present


    - name: Create the Docker service
      community.docker.docker_compose:
        project_src: /home/wagw/COMP90024-Cluster-and-Cloud-Computing-Assignment-2/ansible/mastodon-compose.yaml
        project_name: crawler
        build: false
        scale:
          crawler: "{{ num_replicas }}"

   
    



    

    

