---
- name: Create Docker services
  hosts: swarm_managers 
  become: true
  vars_files:
    - variables/mastodon_vars.yaml 


  #need to fix the building docker images (e.g. soruce, build, dockerfile)
  tasks:
  - name: Build Docker images
    community.docker.docker_image:
      name: "{{ item.name }}"
      source: /home/wagw/COMP90024-Cluster-and-Cloud-Computing-Assignment-2/harvester_node/streamer
      build:
        dockerfile: Dockerfile
      state: present
    loop: "{{ domains }}"

  - name: Create Docker container
    community.general.docker_container:
      name: "{{ item.name }}_container"
      image: "{{ item.name }}"
      state: started
      ports:
        - "8080:80"
    loop: "{{ domains }}"


  #For deleting docker containers  
  - name: Delete Docker container
    community.general.docker_container:
      name: "{{ item.name }}_container"
      state: absent
    loop: "{{ domains }}"


    

    

